# emails
# Source: https://github.com/lockon-n/emails-mcp
# Toolathlon Version: The same
# Cowork_Bench: ../../local_servers/emails-mcp
type: stdio
name: emails
params:
  command: uv
  args:
    - "--directory"
    - "${local_servers_paths}/emails-mcp"
    - "run"
    - "emails-mcp"
    - "--attachment_download_path"
    - "${agent_workspace}/emails_download"
    - "--attachment_upload_path"
    - "${agent_workspace}"
    - "--email_export_path"
    - "${agent_workspace}/emails_export"
    - "--config_file"
    - "${task_dir}/email_config.json"
  # cwd: "${agent_workspace}" # do not add this for compatibility
client_session_timeout_seconds: 120
cache_tools_list: true
