# file system server - for reading and writing files
# Source: https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem
# Toolathlon Version: The same
# Cowork_Bench: ../../local_servers/filesystem
type: stdio
name: filesystem
params:
  command: node
  args:
    - "${local_servers_paths}/filesystem/dist/index.js"
    - "${agent_workspace}"  # only allow reading and writing files in this directory
  cwd: "${agent_workspace}"
client_session_timeout_seconds: 300
cache_tools_list: true