# Google Sheet
# Source: https://github.com/xing5/mcp-google-sheets
# Toolathlon Version: The same
# Cowork_Bench: ../../local_servers/mcp-google-sheets
type: stdio
name: google_sheet
params:
  command: uv
  args:
    - "--directory"
    - "${local_servers_paths}/mcp-google-sheets"
    - "run"
    - "mcp-google-sheets"
  env:
    CREDENTIALS_PATH: ""
    TOKEN_PATH: ""
    DRIVE_FOLDER_ID: ""
  # cwd: "${agent_workspace}" # do not add this for compatibility
client_session_timeout_seconds: 60
cache_tools_list: true