# terminal controller
# Source: https://github.com/MladenSU/cli-mcp-server
# Toolathlon Version: https://github.com/lockon-n/cli-mcp-server
# Cowork_Bench: ../../local_servers/cli-mcp-server
type: stdio
name: terminal
params:
  command: uv
  args:
    - "--directory"
    - "${local_servers_paths}/cli-mcp-server"
    - "run"
    - "cli-mcp-server"
  env:
    # you can add needed commands
    ALLOWED_DIR: "${agent_workspace}"  # only allow reading and writing files in this directory
    ALLOWED_COMMANDS: "ls,cat,pwd,echo,cd,mkdir,touch,rm,cp,mv,find,grep,head,tail,wc,sort,uniq,diff,tree,chmod,stat,file,which,whoami,date,hostname,df,du,ps,env,history,clear,sed,awk,cut,tr,basename,dirname,realpath,md5sum,sha256sum,tar,gzip,gunzip,zip,unzip,less,more,python,wget,curl,ping,netstat,ifconfig,nslookup,traceroute,helm,kubectl,git"
    ALLOWED_FLAGS: "all"
    MAX_COMMAND_LENGTH: "2048"
    COMMAND_TIMEOUT: "60"
    ALLOW_SHELL_OPERATORS: "true"
    MAX_OUTPUT_LENGTH: "10240"
    MAX_STDOUT_LENGTH: "8192"
    MAX_STDERR_LENGTH: "2048"
    CLI_PROXY_ENABLED: "false" # set to true if you want to use a proxy
    CLI_PROXY_URL: "" # set to the proxy url if you want to use a proxy
  cwd: "${agent_workspace}"
client_session_timeout_seconds: 60
cache_tools_list: true