#!/usr/bin/env python3
"""Generate db/zzz_canvas_after_init.sql from canvas_relabel_map.py + live canvas.* data.

Connects to the running cowork_pg (English seed), pulls DISTINCT values per
russifiable (table, column), computes the RU mapping, and emits efficient
temp-map + UPDATE-join blocks (collapsing ~28865 user rows into a few-thousand
value mappings). Course 9991 (rzd, already Russian) is untouched because we key on
the English source values, which never match its Russian content.

Run:  uv run --with psycopg2-binary python3 scripts/canvas_gen_seed_sql.py
"""
import sys, json
sys.path.insert(0, "scripts")
import canvas_relabel_map as M
import psycopg2

DSN = dict(host="localhost", port=15433, dbname="cowork_gym", user="eigent", password="camel")
OUT = "db/zzz_canvas_after_init.sql"

# (table, [columns]) for the generic value-map path
PLAN = [
    ("users", ["name", "sortable_name", "short_name", "bio"]),
    ("courses", ["name", "public_description", "syllabus_body"]),
    ("assignments", ["description"]),
    ("quizzes", ["description"]),
    ("quiz_questions", ["question_text"]),
    ("modules", ["name"]),
    ("assignment_groups", ["name"]),
    ("pages", ["title", "body"]),
    ("discussion_topics", ["title", "message"]),
    ("announcements", ["title", "message"]),
]


def q(s):
    """SQL string literal (single-quote escaped)."""
    return "'" + s.replace("'", "''") + "'"


def main():
    conn = psycopg2.connect(**DSN)
    cur = conn.cursor()
    blocks, stats = [], []
    for table, cols in PLAN:
        for col in cols:
            cur.execute(f'SELECT DISTINCT "{col}" FROM canvas."{table}" WHERE "{col}" IS NOT NULL')
            pairs = []
            for (val,) in cur.fetchall():
                ru = M.map_value(table, col, val)
                if ru is not None and ru != val:
                    pairs.append((val, ru))
            if not pairs:
                stats.append(f"{table}.{col}: 0 (no mappable distinct values)")
                continue
            tmp = f"_map_{table}_{col}"
            lines = [f"-- {table}.{col}: {len(pairs)} distinct value mappings",
                     f"CREATE TEMP TABLE {tmp}(old text PRIMARY KEY, new text);",
                     f"INSERT INTO {tmp}(old,new) VALUES"]
            vals = ",\n".join(f"  ({q(o)},{q(n)})" for o, n in pairs)
            lines.append(vals + ";")
            lines.append(f'UPDATE canvas."{table}" t SET "{col}" = m.new '
                         f'FROM {tmp} m WHERE t."{col}" = m.old;')
            lines.append(f"DROP TABLE {tmp};")
            blocks.append("\n".join(lines))
            stats.append(f"{table}.{col}: {len(pairs)}")

    # submission_comments (jsonb): 11 templated comments + author 'Tutor'->'Преподаватель'
    cur.execute("SELECT DISTINCT submission_comments->0->>'comment' AS c "
                "FROM canvas.submissions WHERE submission_comments IS NOT NULL "
                "AND jsonb_array_length(submission_comments) > 0")
    sc_lines = ["-- submissions.submission_comments: russify comment + author_name (jsonb element 0)"]
    n_sc = 0
    for (com,) in cur.fetchall():
        ru = M.SUBMISSION_COMMENTS.get(com)
        if not ru:
            continue
        sc_lines.append(
            "UPDATE canvas.submissions SET submission_comments = "
            "jsonb_set(jsonb_set(submission_comments, '{0,comment}', " + q(json.dumps(ru, ensure_ascii=False)) + "::jsonb), "
            "'{0,author_name}', '\"Преподаватель\"'::jsonb) "
            "WHERE submission_comments->0->>'comment' = " + q(com) + ";")
        n_sc += 1
    if n_sc:
        blocks.append("\n".join(sc_lines))
    stats.append(f"submissions.submission_comments: {n_sc}")

    header = ("-- AUTO-GENERATED by scripts/canvas_gen_seed_sql.py from scripts/canvas_relabel_map.py\n"
              "-- FULL russification of canvas.* data. Idempotent-by-value: keys on English source\n"
              "-- values, so re-runs are no-ops and course 9991 (rzd, Russian) is never matched.\n"
              "-- DO NOT hand-edit; regenerate from the map.\n")
    with open(OUT, "w") as f:
        f.write(header + "\n" + "\n\n".join(blocks) + "\n")
    cur.close(); conn.close()
    print(f"Wrote {OUT}")
    for s in stats:
        print("  " + s)


if __name__ == "__main__":
    main()
