"""Generate db/zzz_wc_after_init.sql: idempotent UPDATEs that russify the wc.* realia
values (InSales fork of the woocommerce MCP). Mirrors scripts/clickhouse_gen_seed_sql.py.

Reads the actual distinct values from the baked seed (db/init.sql.gz `COPY wc.*` blocks)
COLUMN-AWARE (each data line split on tabs, columns indexed by the COPY header) so we
map exactly what exists. jsonb cells (billing/shipping/line_items/shipping_lines) are
parsed and russified VALUE-AWARE (first_name/last_name/city/country, shipping method_title)
via the single-source-of-truth map scripts/wc_relabel_map.py. product_reviews bodies come
per-id from the merged scripts/wc_reviews_parts/part_*.json.

KEEP English (untouched): products names/sku/suppliers, coupon codes, discount_type,
order status slugs, line_items product names, all ids/slugs/emails/column identifiers.

UPDATE ... WHERE id=<id> (or WHERE col=<en>) is idempotent: re-running is a no-op once
russified (RU values pass through the map unchanged → identical output / no matching <en>).
Runs on next Postgres (re)build via /docker-entrypoint-initdb.d/ (zzz_ ordering).
"""
import glob
import gzip
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import wc_relabel_map as M  # noqa: E402

PROJECT = os.path.dirname(HERE)
SEED = os.path.join(PROJECT, "db", "init.sql.gz")
REVIEW_PARTS = os.path.join(HERE, "wc_reviews_parts", "part_*.json")
OUT = os.path.join(PROJECT, "db", "zzz_wc_after_init.sql")


def parse_copy_blocks(text):
    """Yield (table, [columns], [raw_data_lines]) for each `COPY wc."?table"? (...)` block."""
    lines = text.split("\n")
    i, n = 0, len(lines)
    while i < n:
        ln = lines[i]
        if ln.startswith("COPY wc.") and "FROM stdin;" in ln:
            head = ln[len("COPY wc."):ln.index("(")].strip()
            table = head.strip('"')
            cols = [c.strip().strip('"')
                    for c in ln[ln.index("(") + 1:ln.rindex(")")].split(",")]
            rows = []
            i += 1
            while i < n and lines[i] != "\\.":
                rows.append(lines[i])
                i += 1
            yield table, cols, rows
        i += 1


def sql_str(s):
    """Single-quote a SQL string literal, doubling embedded single quotes.

    Backslashes are kept verbatim (the seed stores newlines as the two-char
    sequence backslash-n inside COPY data, and we preserve that encoding)."""
    return "'" + s.replace("'", "''") + "'"


def jsonb_literal(obj):
    """Serialize a python obj to a Postgres jsonb string literal.

    json.dumps with ensure_ascii=False keeps Cyrillic readable; separators match
    the seed's compact style. Single quotes doubled for the SQL literal."""
    txt = json.dumps(obj, ensure_ascii=False, separators=(", ", ": "))
    return "'" + txt.replace("'", "''") + "'"


def load_reviews():
    """Merge all wc_reviews_parts/part_*.json -> {int_id: review_text}."""
    merged = {}
    for fp in sorted(glob.glob(REVIEW_PARTS)):
        with open(fp, encoding="utf-8") as f:
            d = json.load(f)
        for k, v in d.items():
            merged[int(k)] = v["review"]
    return merged


def map_named_array(val, name_map):
    """Russify a jsonb array of {id, name, ...} elements via name_map (CATEGORIES/TAGS).
    Returns (new_list, changed_bool). Keeps element id and any other keys intact."""
    if not isinstance(val, list):
        return val, False
    changed = False
    out = []
    for el in val:
        if isinstance(el, dict) and "name" in el:
            nm = el["name"]
            ru = name_map.get(nm)
            if ru is not None and ru != nm:
                el = dict(el)
                el["name"] = ru
                changed = True
        out.append(el)
    return out, changed


def map_shipping_lines(val):
    """Russify shipping_lines jsonb: per-element method_title via SHIPPING_METHOD_TITLES.
    Returns (new_list, changed_bool). Keeps ids/method_id/totals."""
    if not isinstance(val, list):
        return val, False
    changed = False
    out = []
    for el in val:
        if isinstance(el, dict) and "method_title" in el:
            mt = el["method_title"]
            ru = M.SHIPPING_METHOD_TITLES.get(mt)
            if ru is not None and ru != mt:
                el = dict(el)
                el["method_title"] = ru
                changed = True
        out.append(el)
    return out, changed


def main():
    with gzip.open(SEED, "rt", encoding="utf-8", errors="replace") as f:
        text = f.read()
    blocks = {table: (cols, rows) for table, cols, rows in parse_copy_blocks(text)}
    reviews = load_reviews()

    out = []
    counts = {}

    def add(line):
        out.append(line)

    add("-- InSales fork: russify wc.* realia values (generated by scripts/wc_gen_seed_sql.py).")
    add("-- Idempotent: id-keyed (or WHERE col=<en>) UPDATEs; numbers/IDs/slugs/enums/emails/")
    add("-- product names/SKUs/coupon codes/line_item product names KEPT English by design.")
    add("-- Source of distinct values: db/init.sql.gz COPY wc.* blocks. Map: scripts/wc_relabel_map.py")
    add("-- Reviews: scripts/wc_reviews_parts/part_*.json (per-id). Runs via /docker-entrypoint-initdb.d/.")
    add("SET client_encoding = 'UTF8';")
    add("")

    def idx_of(cols):
        return {c: k for k, c in enumerate(cols)}

    # ---------------------------------------------------------------- customers
    cols, rows = blocks["customers"]
    ix = idx_of(cols)
    add("-- customers: first_name/last_name (name atoms) + billing/shipping jsonb (value-aware)")
    c = 0
    for r in rows:
        cells = r.split("\t")
        cid = cells[ix["id"]]
        fn, ln = cells[ix["first_name"]], cells[ix["last_name"]]
        rfn = M.CUSTOMER_FIRST.get(fn)
        rln = M.CUSTOMER_LAST.get(ln)
        sets = []
        if rfn is not None and rfn != fn:
            sets.append(f'"first_name"={sql_str(rfn)}')
        if rln is not None and rln != ln:
            sets.append(f'"last_name"={sql_str(rln)}')
        for jcol in ("billing", "shipping"):
            raw = cells[ix[jcol]]
            if raw in ("\\N", ""):
                continue
            try:
                d = json.loads(raw)
            except json.JSONDecodeError:
                continue
            nd = M.map_jsonb_address(d)
            if nd != d:
                sets.append(f'"{jcol}"={jsonb_literal(nd)}')
        if sets:
            add(f'UPDATE wc."customers" SET {", ".join(sets)} WHERE id={cid};')
            c += 1
    counts["customers"] = c
    add("")

    # ----------------------------------------------------------- product_categories
    cols, rows = blocks["product_categories"]
    ix = idx_of(cols)
    add("-- product_categories.name (KEEP slug)")
    c = 0
    for r in rows:
        cells = r.split("\t")
        cid, name = cells[ix["id"]], cells[ix["name"]]
        ru = M.CATEGORIES.get(name)
        if ru is not None and ru != name:
            add(f'UPDATE wc."product_categories" SET "name"={sql_str(ru)} WHERE id={cid};')
            c += 1
    counts["product_categories"] = c
    add("")

    # ----------------------------------------------------------------- product_tags
    cols, rows = blocks["product_tags"]
    ix = idx_of(cols)
    add("-- product_tags.name (KEEP slug)")
    c = 0
    for r in rows:
        cells = r.split("\t")
        cid, name = cells[ix["id"]], cells[ix["name"]]
        ru = M.TAGS.get(name)
        if ru is not None and ru != name:
            add(f'UPDATE wc."product_tags" SET "name"={sql_str(ru)} WHERE id={cid};')
            c += 1
    counts["product_tags"] = c
    add("")

    # --------------------------------------------------------------- shipping_zones
    cols, rows = blocks["shipping_zones"]
    ix = idx_of(cols)
    add("-- shipping_zones.name (KEEP order)")
    c = 0
    for r in rows:
        cells = r.split("\t")
        cid, name = cells[ix["id"]], cells[ix["name"]]
        ru = M.SHIPPING_ZONES.get(name)
        if ru is not None and ru != name:
            add(f'UPDATE wc."shipping_zones" SET "name"={sql_str(ru)} WHERE id={cid};')
            c += 1
    counts["shipping_zones"] = c
    add("")

    # ------------------------------------------------------------- shipping_methods
    cols, rows = blocks["shipping_methods"]
    ix = idx_of(cols)
    add("-- shipping_methods.title (KEEP id flat_rate/free_shipping/local_pickup)")
    c = 0
    for r in rows:
        cells = r.split("\t")
        mid, title = cells[ix["id"]], cells[ix["title"]]
        ru = M.SHIPPING_METHOD_TITLES.get(title)
        if ru is not None and ru != title:
            add(f'UPDATE wc."shipping_methods" SET "title"={sql_str(ru)} WHERE id={sql_str(mid)};')
            c += 1
    counts["shipping_methods"] = c
    add("")

    # -------------------------------------------------------- shipping_zone_methods
    cols, rows = blocks["shipping_zone_methods"]
    ix = idx_of(cols)
    add("-- shipping_zone_methods.method_title (order-level shipping titles; KEEP method_id)")
    c = 0
    for r in rows:
        cells = r.split("\t")
        cid, mt = cells[ix["id"]], cells[ix["method_title"]]
        ru = M.SHIPPING_METHOD_TITLES.get(mt)
        if ru is not None and ru != mt:
            add(f'UPDATE wc."shipping_zone_methods" SET "method_title"={sql_str(ru)} WHERE id={cid};')
            c += 1
    counts["shipping_zone_methods"] = c
    add("")

    # ------------------------------------------------------------- payment_gateways
    cols, rows = blocks["payment_gateways"]
    ix = idx_of(cols)
    add("-- payment_gateways.title + method_title (KEEP id paypal/stripe/cod/bacs)")
    c = 0
    for r in rows:
        cells = r.split("\t")
        gid = cells[ix["id"]]
        title, mtitle = cells[ix["title"]], cells[ix["method_title"]]
        sets = []
        rt = M.PAYMENT_TITLES.get(title)
        if rt is not None and rt != title:
            sets.append(f'"title"={sql_str(rt)}')
        rmt = M.PAYMENT_METHOD_TITLES.get(mtitle)
        if rmt is not None and rmt != mtitle:
            sets.append(f'"method_title"={sql_str(rmt)}')
        if sets:
            add(f'UPDATE wc."payment_gateways" SET {", ".join(sets)} WHERE id={sql_str(gid)};')
            c += 1
    counts["payment_gateways"] = c
    add("")

    # -------------------------------------------------------------------- tax_rates
    cols, rows = blocks["tax_rates"]
    ix = idx_of(cols)
    add("-- tax_rates.name + country (US->Россия) + city (CITY map); KEEP class + state codes")
    c = 0
    for r in rows:
        cells = r.split("\t")
        cid = cells[ix["id"]]
        name = cells[ix["name"]]
        country = cells[ix["country"]]
        city = cells[ix["city"]] if "city" in ix else ""
        sets = []
        rn = M.TAX_NAMES.get(name)
        if rn is not None and rn != name:
            sets.append(f'"name"={sql_str(rn)}')
        rc = M.COUNTRY.get(country)
        if rc is not None and rc != country:
            sets.append(f'"country"={sql_str(rc)}')
        if city not in ("", "\\N"):
            rcity = M.CITY.get(city)
            if rcity is not None and rcity != city:
                sets.append(f'"city"={sql_str(rcity)}')
        if sets:
            add(f'UPDATE wc."tax_rates" SET {", ".join(sets)} WHERE id={cid};')
            c += 1
    counts["tax_rates"] = c
    add("")

    # ------------------------------------------------------------ product_attributes
    cols, rows = blocks["product_attributes"]
    ix = idx_of(cols)
    add("-- product_attributes.name (KEEP slug)")
    c = 0
    for r in rows:
        cells = r.split("\t")
        cid, name = cells[ix["id"]], cells[ix["name"]]
        ru = M.PRODUCT_ATTRIBUTES.get(name)
        if ru is not None and ru != name:
            add(f'UPDATE wc."product_attributes" SET "name"={sql_str(ru)} WHERE id={cid};')
            c += 1
    counts["product_attributes"] = c
    add("")

    # ---------------------------------------------------------------------- coupons
    cols, rows = blocks["coupons"]
    ix = idx_of(cols)
    add("-- coupons.description (KEEP code + discount_type)")
    c = 0
    for r in rows:
        cells = r.split("\t")
        cid, desc = cells[ix["id"]], cells[ix["description"]]
        ru = M.COUPON_DESC.get(desc)
        if ru is not None and ru != desc:
            add(f'UPDATE wc."coupons" SET "description"={sql_str(ru)} WHERE id={cid};')
            c += 1
    counts["coupons"] = c
    add("")

    # ----------------------------------------------------------------------- orders
    cols, rows = blocks["orders"]
    ix = idx_of(cols)
    add("-- orders: billing/shipping jsonb names+city+country, shipping_lines.method_title,")
    add("-- payment_method_title. KEEP line_items product names, status slugs, ids, emails.")
    c = 0
    for r in rows:
        cells = r.split("\t")
        oid = cells[ix["id"]]
        sets = []
        for jcol in ("billing", "shipping"):
            raw = cells[ix[jcol]]
            if raw in ("\\N", ""):
                continue
            try:
                d = json.loads(raw)
            except json.JSONDecodeError:
                continue
            nd = M.map_jsonb_address(d)
            if nd != d:
                sets.append(f'"{jcol}"={jsonb_literal(nd)}')
        # shipping_lines method_title (value-aware)
        raw = cells[ix["shipping_lines"]]
        if raw not in ("\\N", ""):
            try:
                sl = json.loads(raw)
                nsl, ch = map_shipping_lines(sl)
                if ch:
                    sets.append(f'"shipping_lines"={jsonb_literal(nsl)}')
            except json.JSONDecodeError:
                pass
        # payment_method_title (flat text column)
        pmt = cells[ix["payment_method_title"]]
        if pmt not in ("\\N", ""):
            rpmt = M.PAYMENT_METHOD_TITLES.get(pmt) or M.PAYMENT_TITLES.get(pmt)
            if rpmt is not None and rpmt != pmt:
                sets.append(f'"payment_method_title"={sql_str(rpmt)}')
        if sets:
            add(f'UPDATE wc."orders" SET {", ".join(sets)} WHERE id={oid};')
            c += 1
    counts["orders"] = c
    add("")

    # ---------------------------------------------------------------- product_reviews
    cols, rows = blocks["product_reviews"]
    ix = idx_of(cols)
    add("-- product_reviews.review: RU bodies per-id from wc_reviews_parts (reviewer unchanged)")
    c = 0
    missing = []
    for r in rows:
        cells = r.split("\t")
        rid = int(cells[ix["id"]])
        ru = reviews.get(rid)
        if ru is None:
            missing.append(rid)
            continue
        add(f'UPDATE wc."product_reviews" SET "review"={sql_str(ru)} WHERE id={rid};')
        c += 1
    counts["product_reviews"] = c
    add("")

    # -------------------------------------------------------------------- products
    # ONLY the embedded categories/tags jsonb names (InSales GET /products = SELECT *
    # FROM wc.products, no join -> these per-row arrays serve the category/tag names).
    # KEEP English: name/slug/sku/description/short_description/images/attributes/
    # meta_data/price/stock/identifiers. Element id + other keys preserved.
    cols, rows = blocks["products"]
    ix = idx_of(cols)
    add("-- products: ONLY embedded categories/tags jsonb names (CATEGORIES/TAGS map).")
    add("-- KEEP name/slug/sku/description/images/attributes/meta_data/prices/stock English.")
    c = 0
    for r in rows:
        cells = r.split("\t")
        pid = cells[ix["id"]]
        sets = []
        for jcol, name_map in (("categories", M.CATEGORIES), ("tags", M.TAGS)):
            raw = cells[ix[jcol]]
            if raw in ("\\N", ""):
                continue
            try:
                arr = json.loads(raw)
            except json.JSONDecodeError:
                continue
            narr, ch = map_named_array(arr, name_map)
            if ch:
                sets.append(f'"{jcol}"={jsonb_literal(narr)}')
        if sets:
            add(f'UPDATE wc."products" SET {", ".join(sets)} WHERE id={pid};')
            c += 1
    counts["products"] = c
    add("")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")

    total = sum(counts.values())
    print(f"wrote {OUT}")
    for t in sorted(counts):
        print(f"  {t}: {counts[t]}")
    print(f"  TOTAL UPDATEs: {total}")
    if missing:
        print(f"WARNING: {len(missing)} review ids had no RU body: {missing[:20]}")
    return counts, total


if __name__ == "__main__":
    main()
